### ISSUE TITLE
Latest version of BRC does not contain FFmpeg

### ISSUE THREAD

**Issue by eplipswich** [rehdi93/BlenderRenderController#5]
As per title. Not sure why there's a need to remove FFmpeg from the latest version. It's only like about 40MB bigger.

**Comment by red-rj** [comment]
It's because of licencing, when I decided to adopt MIT, I researched the licence of FFmpeg and its really complicated, depending on how you compile FFmpeg, different parts of it have different licences, the pre-build binary I used to include has some of those different bits.

I was unsure how make the proper acknowledgments, so I played safe and didn't include it. Besides, its easy enough to download it your self

**Comment by eplipswich** [comment]
Okay that's understandable. Thanks for the clearup on this.
